### ISSUE TITLE
how to SWITCHER language UI?

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/Meteor-Internationalization#4]
I try add this to my template:

```
// home.html
{{> i18nSwitcher}}
---------------------------
<template name="i18nSwitcher">
  <ul class="">
    {{#each Session 'i18nConfig'}}
      {{> i18nList}}
    {{/each}}
  </ul>
</template>

<template name="i18nList">
{{#if this.value.code}}
  {{#if compare this.value.code '!==' this.currentLocale}}
    <li>
      <a href="#" onclick="i18n.setLocale('{{this.value.code}}'); return false;">{{this.value.name}}</a>
    </li>
  {{/if}}
{{/if}}
</template>
```

but don't show any thing.

**Comment by thearabbit** [comment]
After a try it's not sour, when show , when don't.
I think that it may be problem with user login/out UI (auto clear session).
I use `ian:accounts-ui-bootstrap-3`.

**Comment by dr-dimitru** [comment]
Does `Session` and `compare` helpers available in your app?

**Comment by thearabbit** [comment]
I added already.

**Comment by dr-dimitru** [comment]
Could you please try without ian:accounts-ui-bootstrap-3 package.
Also could you please log ({{log this}}) i18nlist  template and check sessions values via browser console
