### ISSUE TITLE
problem with "ian:accounts-ui-bootstrap-3" package?

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/Meteor-Internationalization#5]
If I add this package 
- before `ian:accounts-ui-bootstrap-3`, It don't work.
- after `ian:accounts-ui-bootstrap-3`, It work fine but UI of `sing in / sing out` can't read (show other label).

**Comment by dr-dimitru** [comment]
Hi @yuomtheara could you please give some code?

**Comment by thearabbit** [comment]
I add this package after `ian:accounts-ui-bootstrap-3`, it work fine.
but the `ian:accounts-ui-bootstrap-3` show the incorrect label.

```
{{> loginButtons}}
```

After I check the `ian:accounts-ui-bootstrap-3`, It have own i18n too.

**Comment by dr-dimitru** [comment]
As I understood ian:accounts-ui-bootstrap-3 should have support of my package, not vise versa.
Is ian:accounts-ui-bootstrap-3 and my package has conflicts?

**Comment by thearabbit** [comment]
Yes, the first time I add `ian:accounts-ui-bootstrap-3` and include `{{> loginButtons}}` on menu bar, it show `sing in / sing up` label on menu bar.
But when i add `i18n`, the `sing in / sing up` menu bar change the label to other words (can't read).

**Comment by dr-dimitru** [comment]
@yuomtheara

> But when i add `i18n`, the `sing in / sing` up menu bar change the label to other words (can't read).
> Which `i18n` you're talking here about, the built-into `ian:accounts-ui-bootstrap-3`? Or this rep?

**Comment by rabbittc** [comment]
built-into ian:accounts-ui-bootstrap-3.

**Comment by dr-dimitru** [comment]
@yuomtheara @rabbittc So you should start issue at `ian:accounts-ui-bootstrap-3` rep
