### ISSUE TITLE
Meteor Example 

### ISSUE THREAD

**Issue by aadamsx** [VeliovGroup/Meteor-Internationalization#6]
Is there a complete Meteor/Blaze and Meteor/React example I can reference?

Thanks!

**Comment by dr-dimitru** [comment]
Hello @aadamsx,

No, but I can give you code-samples from our apps, lib is used at uniq.site and goto.veliov.com
Are you looking for something particular?

**Comment by aadamsx** [comment]
Thanks for the reply. I’m just looking on how to set up with meteor and use it with Blaze. 

I’m in the process of converting Blaze to React, so I’ll need a solution that will make that trip with me so to speak. 

Any help is appreciated. :)

**Comment by dr-dimitru** [comment]
We have expressive examples. With React I assume you're going to use `i18n.get()` method.
You better to provide piece of code where you need to use localized string.

**Comment by aadamsx** [comment]
Sorry for the delay, got tied up with multiple projects.  This is the first of two examples, with the first being a React component INSDIE a Blaze template (as I'm migrating over from Blaze to React).

Below, all the ```text``` I would live to be convertable to different languages, like Spanish, English, etc.

// Code snippits of two react components inside a Blaze template.
```html
<template name="reactBlazeTemplate">
  <nav>
    {{> React component=ReactComponent }}
  </nav>
</template>

```

```javascript
import ReactComponent from './react-component';

Template.reactBlazeTemplate.helpers({
	ReactComponent() {
		return ReactComponent || null;
	}
});
```

```javascript
// react-component.js
...

  let content;
  if (mode !== 'AOS') {
    content = 
      <div style={Style}>
        <li style={Style}>
          <SidebarNavigation text="Relationships" mode={mode} />
        </li>
        <li style={Style}>
          <SidebarNavigation text="Employment" mode={mode} />
        </li>
      </div>
  }

  return (  
    <ul>
      <li key={1} style={Style}>
        <SidebarNavigation text="Status" mode={mode} />
      </li>
      <li style={Style}>
        <SidebarNavigation text="Bio" mode={mode}/>
      </li>
      {content}
    </ul>
  );
}

...
```
```javascript
// sidebar.js
const SidebarNavigation = ({ text, mode }) => {
...

  return (
    <div>
      <button id={btnId} onClick={() => FlowRouter.go(routeId)} className="btn-link" style={bStyle}>{text}</button>
    </div>
  );
}

export default SidebarNavigation;
```

The next STRAIGHT Blaze example is coming...

**Comment by aadamsx** [comment]
This is a straigt Blaze exmaple.  Here I'd like all the Text to be convertable to different languages:
```html
<template name="activity">
  <h3>Part 3.5 Activity</h3>
    ...
    <div class="well bs-component">
        {{#autoForm collection="Activity" id="ctivityForm" doc=doc type=type class="form-horizontal"}}
          <h4>Activity</h4>
          <label class="floating-label label-special4">All questions are about the Alien (foreign citizen).</label>
          <label class="floating-label label-special2">Has The Activity contributed to or worked for any charitable organizations?</label>
          {{> inputControlRadio2 name="socialOrgs" classes="radio-click-event"}}
          {{#if radio_state "socialOrgs"}}
            <label class="floating-label label-special2">Add one or more organizations.</label>
            ...
          {{/if}}
          <hr>
          {{> inputControlRadio2 name="convictions" classes="radio-click-event"}}
          {{#if radio_state "organizations"}}
            {{> inputControlTextArea name="convictionsExplained" title="Explain all organizations"}}
          {{/if}}
        {{/autoForm}}
    </div>
    ...
</template>
```

```javascript
Template.activity.onCreated(function() {
    
});

Template.activity.helpers({
  radio_state: function(field) { 
    ...
  }
});

Template.activity.events({
  'click .radio-click-event': function(e, tmpl) {
    ...
  }
});
```

**Comment by aadamsx** [comment]
This is a question I posted on this toipc here in the Meteor forum just in case:

https://forums.meteor.com/t/any-examples-i18n-with-meteor-blaze-react/48388/2

**Comment by dr-dimitru** [comment]
Config:

```js
const i18nConfig = {
  settings: {
    defaultLocale: "en",
    ru: {
      code: "ru",
      isoCode: "ru-RU",
      name: "Русский"
    },
    en: {
      code: "en",
      isoCode: "en-US",
      name: "English"
    }
  },
  ru: {
    property: "значение",
  },
  en: {
    property: "value"
  }
};
```

Initialize:

```js
import I18N from 'meteor/ostrio:i18n';
const i18n = new I18N({i18n: i18nConfig});
```

React:

```js
i18n.setLocale('en');
i18n.get('property'); // -> value

i18n.setLocale('ru');
i18n.get('property'); // -> значение
```

You can use same in a Blaze helpers, or use *TemplateHelper* `i18n`:

```handlebars
<p>{{i18n 'property'}}</p> <!-- value -->
```

**Comment by dr-dimitru** [comment]
Feel free to close it in case if the issue is solved on your end.

**Comment by aadamsx** [comment]
Thanks!

**Comment by dr-dimitru** [comment]
@aadamsx I'm glad this issue is solved.

Please support this project with:
 - Star this package on GitHub: https://github.com/VeliovGroup/Meteor-Internationalization
 - Like at Facebook: https://www.facebook.com/veliovgroup
 - Follow on Twitter: https://twitter.com/veliovgroup
 - Check and star our other open source projects on GitHub: https://github.com/VeliovGroup

**Comment by aadamsx** [comment]
I will and have. Are you guys trying to drum up business these days?

**Comment by dr-dimitru** [comment]
@aadamsx thank you. We've always been doing that.
