### ISSUE TITLE
Can all properties be stored in a separate json or yml file per language?

### ISSUE THREAD

**Issue by carlosalvidrez** [VeliovGroup/Meteor-Internationalization#7]
Hi thanks for sharing this. Quick question: Can all properties be stored in a separate json or yml file per language?

The readme file seems to indicate a path to a file for each language/locale, but I can't find a specific example... not sure if the file should be JSON or YML or if the name matters.

path: "i18n/ru/"

**Comment by dr-dimitru** [comment]
Hello @carlosalvidrez ,

Yes, just import file and add localization, example:

```js
import loc from '/path/to/localization.json';

i18n.addl10n({
  en: loc // <- Object's root is the language two-letter code
});
```

hope that helps, let me know

**Comment by dr-dimitru** [comment]
`yml` not supported

**Comment by carlosalvidrez** [comment]
Thanks @dr-dimitru !
I will have about 50 languages... do you have any advice on how to create a dynamic import for the user's locale? 
Seems like I won't know the locale until I initialize i18n, so I am not sure how to do this.

Will try this thanks!!

**Comment by dr-dimitru** [comment]
Not sure if this will work but you can try next:

1. Have `/i18n/index.js` file where all other localizations are `import`ed
2. Import `/i18n/index.js` on a server, and load all localizations on a server
3. have a route like `/:lang/path` use `param.lang` to build a path to the localization file passed to dynamic `import()`

Try and let me know

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
